version: 0.2

phases:
  # install:
  #   runtime-versions:
  #     nodejs: "16.x"
  pre_build:
    commands:
      - echo "Checking Node Version"
      - node -v
      - echo "Checking NPM Version"
      - npm -v
      - echo "Installing base packages"
      - npm install

  build:
    commands:
      - echo "Generating static files"
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
